@startuml

hide methods

object Appliance {
    -String name
}

object Property {
    -String name
}

object PropertyValue {
    -String value
}

object Model {
    -String modelNum
    -File manual
}

object Brand {
    -String designation
}

object Part {
     -String name
     -String partNum
}

object StockItem {
    -String code
    -String location
    -Integer stock
}

Part "*" --> "1" Model: collected from >
Part "*" --> "*" Model: compatible with >
Part "1" --> "1" StockItem: is one >
Part "1" --> "1" Brand: is made by >

Model "1" --> "1" Brand: is made by >
Model "1" --> "1" Appliance: is a >

Appliance "1" --> "*" Property: has >
Property "1" --> "1" PropertyValue: corresponds to >
Part "1" --> "*" PropertyValue: has >

@enduml